const express = require('express');
const router = express.Router();
const upload = require('../../middlewares/upload');
const courseController = require('../../controllers/admin/courseController');
router.post('/', upload.fields([{ name: "imageUrl" }, { name: "videoUrl" }]), courseController.createCourse);
router.get('/', courseController.getCourses);
router.get('/:id', courseController.getCourseById);
router.put('/:id', upload.fields([{ name: "imageUrl" }, { name: "videoUrl" }]), courseController.updateCourse);
router.delete('/:id', courseController.deleteCourse);
module.exports = router;